### PR TITLE
[Fix #52] Clean up changelog and releasing files

### LINKED ISSUE #52: Clean up releases notes
Change the ordering and add some more info

### PR DESCRIPTION
**Pull request by roman-dubrovsky**

### CODE REVIEW

**Comment by AleksSenkou** [comment]
@roman-dubrovsky what is the reason to go with dots?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou this is just punctuation at the end of a sentence, isn't it?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky yeah 😃 
Was wondering, maybe it's kind of convention. Just feel dots redundant in such cases

**Comment by roman-dubrovsky** [comment]
> Was wondering, maybe it's kind of convention. Just feel dots redundant in such cases

I don't know, for me, it looks better with dots

**Pull request merged**
