### PR TITLE
[Fix #50] Update rubocop version to 0.73

### LINKED ISSUE #50: Update to RuboCop 0.73
Todo:

* [x] check `rubocop-rspec`
* [x] check changle logs
* [x] update versions 
* [x] check required ruby version
* [x] verify that new version works correctly
* [x] add changelog note

Links:

https://github.com/rubocop-hq/rubocop/releases/tag/v0.73.0

### PR DESCRIPTION
**Pull request by roman-dubrovsky**
TODO list here #50

### CODE REVIEW

**Comment by AleksSenkou** [comment]
Can we somehow control rubocop version so that we see that we are at the latest all the time?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou sorry, I don't understand your question

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I mean to know if we are at the latest rubocop version. Maybe we can add a badge to the readme showing if we are on the latest version

Is it better?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I still don't understand your idea. Why should we do it? Or how can this badge help us? 

Anyway, let's continue this discussion in the separate issue (fill free to create a new one) or in the slack

**Pull request merged**
