### PR TITLE
[Close #125] Setup Github Actions

### LINKED ISSUE #125: Setup CircleCI
Check rubocop config and Rspec tests

### PR DESCRIPTION
**Pull request by lazycoder9**
Before you submit a pull request, please make sure you have to follow:

- [x] read and know items from the [Contributing Guide](https://github.com/datarockets/datarockets-style/blob/master/CONTRIBUTING.md#pull-requests)
- [x] add a description of the problem you're trying to solve (short summary from related issue)
- [x] verified that cops are ordered by alphabet
- [x] add a note to the style guide docs (if it needs)
- [x] add a note to the changelog file
- [x] the commit message contains the number of the related issue (if it presents)
  and word `Fix` if this PR closes related issue
- [x] squash all commits before submitting to review

Close #125

### CODE REVIEW

**Comment by roman-dubrovsky** [comment]
@lazycoder9 can you also run a rubocop in github actions?

**Comment by lazycoder9** [comment]
@roman-dubrovsky what do you think about creating `Makefile` with `install`, `test` and `lint` commands? I could do it in this PR

**Comment by roman-dubrovsky** [comment]
@lazycoder9 ok, let's try

**Comment by lazycoder9** [comment]
@roman-dubrovsky check it out

**Pull request merged**
